package dev.kpp.gradle

import dev.kpp.analyzer.ConsoleReporter
import dev.kpp.analyzer.KppScanner

/**
 * Runs the Kotlin++ regex analyzer over the configured source roots.
 * Reports violations through ConsoleReporter; fails the task if any
 * non-suppressed ERROR-severity violations remain and failOnViolation = true.
 */
abstract class KppCheckTask : org.gradle.api.DefaultTask() {
    @get:org.gradle.api.tasks.Input
    abstract val sourceRoots: org.gradle.api.provider.ListProperty<java.io.File>

    @get:org.gradle.api.tasks.Input
    abstract val suppressedRules: org.gradle.api.provider.SetProperty<String>

    @get:org.gradle.api.tasks.Input
    abstract val failOnViolation: org.gradle.api.provider.Property<Boolean>

    @org.gradle.api.tasks.TaskAction
    fun run() {
        // Filter source roots to only those that exist at task-run time.
        // We do not filter at config time because the directories might be
        // generated by an earlier task in the same build (e.g. code generation),
        // and applying a configuration-time filter would freeze a stale answer.
        val existingRoots = sourceRoots.get().filter { it.exists() }
        val suppressed = suppressedRules.get()

        val scanner = KppScanner(existingRoots)
        val violations = scanner.scan().filter { it.ruleId !in suppressed }

        val reporter = ConsoleReporter()
        val exitCode = reporter.report(violations)

        if (failOnViolation.get() && exitCode != 0) {
            throw org.gradle.api.GradleException("kppCheck found ${violations.size} violation(s)")
        }
    }
}
